openapi: 3.0.0
info:
  description: >-
    This project can be used to recommend instance type groups on different
    cloud providers consisting of regular and spot/preemptible instances.

    The main goal is to provide and continuously manage a cost-effective but
    still stable cluster layout that's built up from a diverse set of regular
    and spot instances.
  title: Cluster Recommender.
  contact:
    name: Banzai Cloud
    email: info@banzaicloud.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 0.0.1
paths:
  '/products/:provider/:region':
    get:
      tags:
        - products
      summary: >-
        Provides a list of available machine types on a given provider in a
        specific region.
      operationId: getProductDetails
      responses:
        '200':
          $ref: '#/components/responses/productDetailsResponse'
  '/recommender/:provider/:region/cluster':
    post:
      tags:
        - recommend
      summary: >-
        Provides a recommended set of node pools on a given provider in a
        specific region.
      operationId: recommendClusterSetup
      parameters:
        - x-go-name: SumCpu
          description: Total number of CPUs requested for the cluster
          name: sumCpu
          in: query
          schema:
            type: number
            format: double
        - x-go-name: SumMem
          description: Total memory requested for the cluster (GB)
          name: sumMem
          in: query
          schema:
            type: number
            format: double
        - x-go-name: MinNodes
          description: Minimum number of nodes in the recommended cluster
          name: minNodes
          in: query
          schema:
            type: integer
            format: int64
        - x-go-name: MaxNodes
          description: Maximum number of nodes in the recommended cluster
          name: maxNodes
          in: query
          schema:
            type: integer
            format: int64
        - x-go-name: SameSize
          description: 'If true, recommended instance types will have a similar size'
          name: sameSize
          in: query
          schema:
            type: boolean
        - x-go-name: OnDemandPct
          description: Percentage of regular (on-demand) nodes in the recommended cluster
          name: onDemandPct
          in: query
          schema:
            type: integer
            format: int64
        - x-go-name: Zones
          description: Availability zones that the cluster should expand to
          name: zones
          in: query
          schema:
            type: array
            items:
              type: string
        - x-go-name: SumGpu
          description: Total number of GPUs requested for the cluster
          name: sumGpu
          in: query
          schema:
            type: integer
            format: int64
        - x-go-name: AllowBurst
          description: Are burst instances allowed in recommendation
          name: allowBurst
          in: query
          schema:
            type: boolean
        - x-go-name: NetworkPerf
          description: NertworkPerf specifies the network performance category
          name: networkPerf
          in: query
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/recommendationResp'
  '/regions/:provider':
    get:
      description: Provides the list of available regions of a cloud provider
      tags:
        - regions
      operationId: getRegions
      responses:
        '200':
          $ref: '#/components/responses/regionsResponse'
servers:
  - url: /api/v1
components:
  responses:
    productDetailsResponse:
      description: ProductDetailsResponse Api object to be mapped to product info response
      headers:
        Products:
          description: >-
            Products represents a slice of products for a given provider (VMs
            with attributes and process)
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ProductDetails'
    recommendationResp:
      description: ClusterRecommendationResp encapsulates recommendation result data
      headers:
        nodePools:
          description: Recommended node pools
          schema:
            type: array
            items:
              $ref: '#/components/schemas/NodePool'
        provider:
          description: The cloud provider
          schema:
            type: string
        zones:
          description: >-
            Availability zones in the recommendation - a multi-zone
            recommendation means that all node pools should expand to all zones
          schema:
            type: array
            items:
              type: string
    regionsResponse:
      description: RegionResp holds the list of available regions of a cloud provider
      headers:
        id:
          schema:
            type: string
        name:
          schema:
            type: string
  schemas:
    NodePool:
      description: NodePool represents a set of instances with a specific vm type
      type: object
      properties:
        sumNodes:
          description: Recommended number of nodes in the node pool
          type: integer
          format: int64
          x-go-name: SumNodes
        vm:
          $ref: '#/components/schemas/VirtualMachine'
        vmClass:
          description: >-
            Specifies if the recommended node pool consists of regular or
            spot/preemptible instance types
          type: string
          x-go-name: VmClass
      x-go-package: github.com/banzaicloud/telescopes/recommender
    ProductDetails:
      description: apart of the VmInfo it may hold derived or additional information
      type: object
      title: ProductDetails extended view of the virtual machine details.
      properties:
        burst:
          description: Burst this is derived for now
          type: boolean
          x-go-name: Burst
        cpusPerVm:
          type: number
          format: double
          x-go-name: Cpus
        gpusPerVm:
          type: number
          format: double
          x-go-name: Gpus
        memPerVm:
          type: number
          format: double
          x-go-name: Mem
        ntwPerf:
          type: string
          x-go-name: NtwPerf
        onDemandPrice:
          type: number
          format: double
          x-go-name: OnDemandPrice
        spotPrice:
          type: array
          items:
            $ref: '#/components/schemas/ZonePrice'
          $ref: '#/components/schemas/SpotPriceInfo'
        type:
          type: string
          x-go-name: Type
      x-go-package: github.com/banzaicloud/telescopes/productinfo
    SpotPriceInfo:
      description: SpotPriceInfo represents different prices per availability zones
      type: object
      additionalProperties:
        type: number
        format: double
      x-go-package: github.com/banzaicloud/telescopes/productinfo
    VirtualMachine:
      description: VirtualMachine describes an instance type
      type: object
      properties:
        avgPrice:
          description: >-
            Average price of the instance (differs from on demand price in case
            of spot or preemptible instances)
          type: number
          format: double
          x-go-name: AvgPrice
        burst:
          description: Burst signals a burst type instance
          type: boolean
          x-go-name: Burst
        cpusPerVm:
          description: Number of CPUs in the instance type
          type: number
          format: double
          x-go-name: Cpus
        gpusPerVm:
          description: Number of GPUs in the instance type
          type: number
          format: double
          x-go-name: Gpus
        memPerVm:
          description: Available memory in the instance type (GB)
          type: number
          format: double
          x-go-name: Mem
        networkPerf:
          description: NetworkPerf holds the network performance category
          type: string
          x-go-name: NetworkPerf
        onDemandPrice:
          description: Regular price of the instance type
          type: number
          format: double
          x-go-name: OnDemandPrice
        type:
          description: Instance type
          type: string
          x-go-name: Type
      x-go-package: github.com/banzaicloud/telescopes/recommender
    ZonePrice:
      description: ZonePrice struct for displaying proce information per zone
      type: object
      properties:
        price:
          type: string
          x-go-name: Price
        zone:
          type: string
          x-go-name: Zone
      x-go-package: github.com/banzaicloud/telescopes/productinfo

