run:
    skip-dirs:
        - .gen
        - client

linters-settings:
    golint:
        min-confidence: 0.9

    gocyclo:
        min-complexity: 15

linters:
    enable-all: true
#        - misspell
#        - gofmt
#        - golint
#        - goimports
#        - gochecknoglobals
    disable:
        - errcheck
        - gas
        - megacheck
        - varcheck
