run:
    skip-dirs:
        - .gen
        - client

linters-settings:
    golint:
        min-confidence: 0.9

    gocyclo:
        min-complexity: 20

    lll:
        line-length: 200

linters:
    enable-all: true
    #        - misspell
    #        - gofmt
    #        - golint
    #        - goimports
    #        - gochecknoglobals
    disable:
        - gocritic
#        - errcheck
#        - gas
#        - megacheck
#        - varcheck

