[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  name = "github.com/banzaicloud/cloudinfo"
  version = "0.4.5"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/banzaicloud/bank-vaults"
  version = "0.2.26"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/banzaicloud/go-gin-prometheus"

[[constraint]]
  name = "github.com/goph/emperror"
  version = "0.12.0"

[[constraint]]
  name = "github.com/moogar0880/problems"
  version = "0.1.0"
